[package]
name = "learn-quicksilver"
version = "0.1.0"
authors = ["Zacharie Day <day@gwu.edu>"]
edition = "2018"

[dependencies]
quicksilver = "*"
rand = "0.6.5"
splines = "0.2.0"

[[bin]]
name = "learn-quicksilver"
path = "src/main.rs"
